version: '3.8'
services:
  redis-node1:
    image: redis:latest
    container_name: redis-node1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./node:/usr/local/etc/redis
    ports:
      - "6379:6379"
    networks:
      - redis-cluster

  redis-node2:
    image: redis:latest
    container_name: redis-node2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./node:/usr/local/etc/redis
    ports:
      - "6380:6379"
    networks:
      - redis-cluster

  redis-node3:
    image: redis:latest
    container_name: redis-node3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./node:/usr/local/etc/redis
    ports:
      - "6381:6379"
    networks:
      - redis-cluster

  redis-node4:
    image: redis:latest
    container_name: redis-node4
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./node:/usr/local/etc/redis
    ports:
      - "6382:6379"
    networks:
      - redis-cluster

  redis-node5:
    image: redis:latest
    container_name: redis-node5
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./node:/usr/local/etc/redis
    ports:
      - "6383:6379"
    networks:
      - redis-cluster

  redis-node6:
    image: redis:latest
    container_name: redis-node6
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./node:/usr/local/etc/redis
    ports:
      - "6384:6379"
    networks:
      - redis-cluster
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - redis-cluster
    
volumes:
  node_modules:

networks:
  redis-cluster:
    driver: bridge
